FROM mysql:5.7

# download database .zip
RUN echo "Download dataBase.zip"

# unzip db.zip
RUN echo "unzip dataBase.zip"

# create db
RUN echo "Create new data base"

# import database
RUN echo "import data base"

# start myqld.service
RUN systemctl start myqld.service \
    systemctl status mysqld.service